---
# Handlers for PostgreSQL role

- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    daemon_reload: true

- name: Reload postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: reloaded

- name: Stop postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
